config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  devise_for :users
  resources :facilities
  resources :carriers
  resources :contacts
  resources :messages

  resources :carriers do
    resources :contacts
    resources :facilities
  end

  root 'static_pages#home'

  get 'carrier/:id/remove_nda', to: 'carriers#remove_nda', as: 'remove_carrier_nda'
  get 'carrier/:id/remove_contract', to: 'carriers#remove_contract', as: 'remove_carrier_contract'

end

app/models/carrier.rb
class Carrier < ActiveRecord::Base
  has_many :facilities, dependent: :destroy
  has_many :contacts, dependent: :destroy
  validates :name, :presence => true
  
  has_attached_file :nda, styles: { large: "200x200" }
  validates_attachment_content_type :nda, :content_type => ["image/jpg", "image/jpeg",
            "image/png", "image/gif", "application/pdf","application/vnd.ms-excel",
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            "application/msword", 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
            "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            "text/plain"]
  validates_attachment_file_name :nda, :matches => [/png\Z/, /jpe?g\Z/, /gif\Z/, /pdf\Z/, /xlsx?\Z/, /docx\Z/, /doc\Z/, /txt\Z/]

  has_attached_file :contract, styles: { large: "200x200" }
  validates_attachment_content_type :contract, :content_type => ["image/jpg", "image/jpeg",
            "image/png", "image/gif", "application/pdf","application/vnd.ms-excel",
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            "application/msword", 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
            "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            "text/plain"]
  validates_attachment_file_name :contract, :matches => [/png\Z/, /jpe?g\Z/, /gif\Z/, /pdf\Z/, /xlsx?\Z/, /docx\Z/, /doc\Z/, /txt\Z/]

  def imagecontract?
    contract_content_type =~ %r{^(image|(x-)?application)/(bmp|gif|jpeg|jpg|pjpeg|png|pdf|x-png)$}
  end

  def imagenda?
    nda_content_type =~ %r{^(image|(x-)?application)/(bmp|gif|jpeg|jpg|pjpeg|png|pdf|x-png)$}
  end

  private

  def resize_images
    return false unless image?
  end

  def self.search(search)
    where("lower(name) LIKE ? OR lower(comments) LIKE ?", "%#{search}%".downcase, "%#{search}%".downcase)
  end
end

app/controllers/carriers_controller.rb
class CarriersController < ApplicationController
  before_action :set_carrier, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:new, :create]

  # GET /carriers
  # GET /carriers.json
  def index
    @carriers = Carrier.all.order(:name)

    if params[:search]
      @carriers = Carrier.search(params[:search])
    else
      @carriers = Carrier.all.order(:name)
    end
  end

  def remove_nda
    @carrier = Carrier.find(params[:id])
    @carrier.nda = nil
    @carrier.save
    redirect_to @carrier, flash: { success: 'The NDA has been deleted. It will be missed.'}
  end

  def remove_contract
    @carrier = Carrier.find(params[:id])
    @carrier.contract = nil
    @carrier.save
    redirect_to @carrier, flash: { success: 'The Contract has been deleted. It will be missed.'}
  end
  # GET /carriers/1
  # GET /carriers/1.json
  def show
  end

  # GET /carriers/new
  def new
    @carrier = Carrier.new
  end

  # GET /carriers/1/edit
  def edit
  end

  # POST /carriers
  # POST /carriers.json
  def create
    @carrier = Carrier.new(carrier_params)

    respond_to do |format|
      if @carrier.save
        if !current_user.admin?
          current_user.update_attribute :carrier_name, @carrier.name
        end

        # FormMailer.carrier_email(@carrier.name, @carrier.id).deliver
        format.html { redirect_to :root, notice: 'Thank you for registering! We will contact you for future opportunities.' }
        format.json { render :root, status: :created, location: @carrier }
      else
        format.html { render :new }
        format.json { render json: @carrier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carriers/1
  # PATCH/PUT /carriers/1.json
  def update
    respond_to do |format|
      if @carrier.update(carrier_params)
        format.html { redirect_to @carrier, notice: 'Carrier was successfully updated.' }
        format.json { render :show, status: :ok, location: @carrier }
      else
        format.html { render :edit }
        format.json { render json: @carrier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carriers/1
  # DELETE /carriers/1.json
  def destroy
    @carrier.destroy
    respond_to do |format|
      format.html { redirect_to carriers_url, notice: 'Carrier was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_carrier
      @carrier = Carrier.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def carrier_params
      params.require(:carrier).permit(:name, :exp_in_retail, :exp_in_intl_cargo, :exp_in_garments_on_hangars, :exp_in_noncommercial_goods, :exp_in_replenishment, :exp_in_shop_returns, :two_year_contract, :operate_year_round, :handle_cosmetic_products, :accept_payment_in_thirty_days, :comments, :nda, :contract, :sort_and_segregate, :pool_distribution, :participate_in_recycling_programs, :scanning, :scanning_software, :final_mile_or_linehaul)
    end
end

app/helpers/carriers_helper.rb
module CarriersHelper
end

app/views/carriers/_form.html.erb
<%= form_for @carrier, html: { multipart: true } do |f| %>
  <% if @carrier.errors.any? %>
    <div class="alert alert-danger alert-dismissible" id="error_explanation" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <% @carrier.errors.full_messages.each do |message| %>
        <p><%= message %></p>
      <% end %>
    </div>
  <% end %>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Name</h3>
    </div>
    <div class="panel-body">
      <div class="field">
        <%= f.label :name %><br>
        <%= f.text_field :name %>
      </div>
      <div class="field">
        <%= f.radio_button :final_mile_or_linehaul, "Final Mile" %>Final Mile<br>
        <%= f.radio_button :final_mile_or_linehaul, "Linehaul" %>Linehaul<br>
        <%= f.radio_button :final_mile_or_linehaul, "Final Mile and Linehaul" %>Final Mile and Linehaul<br>
      </div>
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Experience In</h3>
    </div>
    <div class="panel-body">
      <div class="field">
        <%= f.check_box :exp_in_retail %> <strong>Retail</strong>
      </div>
      <div class="field">
        <%= f.check_box :exp_in_intl_cargo %> <strong>Receiving International Cargo</strong>
      </div>
      <div class="field">
        <%= f.check_box :exp_in_garments_on_hangars %> <strong>Receiving of Garments on Hangers</strong>
      </div>
      <div class="field">
        <%= f.check_box :exp_in_noncommercial_goods %> <strong>Receiving of Non-Commercial Goods</strong>
      </div>
      <div class="field">
        <%= f.check_box :exp_in_replenishment %> <strong>Allocation to Stores or Warehouses' Replenishment Section</strong>
      </div>
      <div class="field">
        <%= f.check_box :exp_in_shop_returns %> <strong>Handling of Shop Returns</strong>
      </div>
      <div class="field">
        <%= f.check_box :sort_and_segregate %> <strong>Sort and Segregate</strong>
      </div>
      <div class="field">
        <%= f.check_box :pool_distribution %> <strong>Pool Distribution</strong>
      </div>
      <div class="field">
        <%= f.check_box :participate_in_recycling_programs %> <strong>Participate in Recycling Programs</strong>
      </div>
      <div class="field">
        <%= f.check_box :scanning %> <strong>Use Barcode Scanning</strong>
      </div>
      <div class="field">
        <%= f.label "If so, what software is used?" %><br>
        <%= f.text_field :scanning_software %>
      </div>
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">General Operations</h3>
    </div>
    <div class="panel-body">
      <div class="field">
        <%= f.check_box :two_year_contract %> <strong>Ability To Agree On A Two Year Contract</strong>
      </div>
      <div class="field">
        <%= f.check_box :operate_year_round %> <strong>Ability To Operate 7 Days A Week And On Bank Holidays</strong>
      </div>
      <div class="field">
        <%= f.check_box :handle_cosmetic_products %> <strong>Ability To Handle Cosmetic Products</strong>
      </div>
      <div class="field">
        <%= f.check_box :accept_payment_in_thirty_days %> <strong>Accept 30 Day Payment Terms</strong>
      </div>
    </div>
  </div>

<% if current_user.try(:admin?) %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Attach Files</h3>
    </div>
    <div class="panel-body">
      <div class="form-group">
        <%= f.label :nda, 'Attach an NDA' %><br>
        <%= f.file_field :nda %>
      </div>
      <div class="form-group">
        <%= f.label :contract, 'Attach a Contract' %><br>
        <%= f.file_field :contract %>
      </div>
    </div>
  </div>
<% end %>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Additional Info</h3>
    </div>
    <div class="panel-body">
      <div class="form-group">
        <%= f.label :comments %><br>
        <%= f.text_area :comments, :rows => "4", :class => 'form-control' %>
      </div>
    </div>
  </div>

  <p class="text-muted">This form contains proprietary information, trade secret information, copyrighted materials, or any combination thereof and will not be reproduced, published, used, or otherwise disseminated without your express written permission. The contents of this form are protectable under the Economic Espionage Act, 18 U.S.C. §1831 et seq., the Electronic Communications Privacy Act, 18 U.S.C. §2510 et seq., the Copyright Act, 17 U.S.C. §101 et seq., the Michigan Uniform Trade Secret Act §445.1901 et seq., as well as common law; applicable law provides criminal remedies, civil remedies, or both for the unauthorized reproduction, publication, use, or dissemination of the contents of this form or any attached files.  This form is intended solely for the use of the individual or entity addressed above; if you have received this form in error, please notify the sender.</p>

  <div class="actions">
    <%= f.submit 'Submit', :class => 'btn btn-primary' %>
  </div>
  <hr>
<% end %>

app/views/carriers/edit.html.erb
<h1>Editing Carrier</h1>

<%= render 'form' %>

<div class="btn-group">
  <%= link_to 'Show', @carrier, class: 'btn btn-default' %>
  <%= link_to 'Back', carriers_path, class: 'btn btn-default' %>
</div>

app/views/carriers/index.html.erb
<h1>Carriers</h1>

<div class="well" style="margin: 40px 0;">
  <div class="row">
    <div class="col-sm-8">
      <%= form_tag(carriers_path, :method => "get", id: "search-form", class: 'form-inline') do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search Carriers", class: 'form-control' %>
        <%= submit_tag "Search", class: 'btn btn-primary' %>
        <%= link_to 'Reset', carriers_path, class: 'btn btn-default' =%>
      <% end %>
    </div>
    <div class="col-sm-4">
      <%= link_to new_carrier_path, class: 'btn btn-success pull-right' do %>
        <i class="glyphicon glyphicon-plus" aria-hidden="true"></i> New Carrier
      <% end %>
    </div>
  </div>
</div>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Capabilities</th>
      <th>Experience in Retail</th>
      <th>Comments</th>
      <th>Edit / Delete</th>
    </tr>
  </thead>

  <tbody>
    <% @carriers.each do |carrier| %>
      <tr>
        <td><%= link_to carrier.name, carrier %>
          <% if carrier.nda? %>
            - <i class="glyphicon glyphicon-file" aria-hidden="true"></i>
          <% end %>
        </td>
        <td><%= carrier.final_mile_or_linehaul %></td>
        <td><%= boolean_yesno(carrier.exp_in_retail) %></td>
        <td><%= carrier.comments %></td>
        <td>
          <div class="btn-group" role="group" aria-label="...">
            <%= link_to edit_carrier_path(carrier), class: 'btn btn-default' do %>
              <i class="glyphicon glyphicon-edit" aria-hidden="true"></i>
            <% end %>
            <%= link_to carrier, method: :delete, data: { confirm: 'Woah! Careful, buddy. If you delete this carrier, it will delete all its associated contacts and facilities as well. Are you sure you want to do this?' }, class: 'btn btn-danger' do %>
              <i class="glyphicon glyphicon-trash" aria-hidden="true"></i>
            <% end %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<p>
<i class="glyphicon glyphicon-file" aria-hidden="true"></i>
- A valid NDA is uploaded.
</p>
<p>
<i class="glyphicon glyphicon-warning-sign text-danger" aria-hidden="true"></i>
- The uploaded NDA has expired.
</p>

app/views/carriers/new.html.erb
<h1>New Carrier</h1>

<%= render 'form' %>

<% if current_user.try(:admin?) %>
  <%= link_to 'Back', carriers_path, class: 'btn btn-default' %>
<% else %>
  <%= link_to 'Back', root_path, class: 'btn btn-default' %>
<% end %>

app/views/carriers/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Location</h3>
  </div>
  <div class="panel-body">
    <p>
      <strong>Name:</strong>
      <%= @carrier.name %>
    </p>
    <p>
      <strong>Capabilities:</strong>
      <%= @carrier.final_mile_or_linehaul %>
    </p>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Experience In</h3>
  </div>
  <div class="panel-body">
    <p>
      <strong>Retail:</strong>
      <%= boolean_yesno(@carrier.exp_in_retail) %>
    </p>
    <p>
      <strong>Receiving International Cargo:</strong>
      <%= boolean_yesno(@carrier.exp_in_intl_cargo) %>
    </p>
    <p>
      <strong>Receiving of Garments on Hangers:</strong>
      <%= boolean_yesno(@carrier.exp_in_garments_on_hangars) %>
    </p>
    <p>
      <strong>Receiving of Non-Commercial Goods:</strong>
      <%= boolean_yesno(@carrier.exp_in_noncommercial_goods) %>
    </p>
    <p>
      <strong>Allocation to Stores or Warehouses' Replenishment Section:</strong>
      <%= boolean_yesno(@carrier.exp_in_replenishment) %>
    </p>
    <p>
      <strong>Handling of Shop Returns:</strong>
      <%= boolean_yesno(@carrier.exp_in_shop_returns) %>
    </p>
    <p>
      <strong>Sort and Segregate:</strong>
      <%= boolean_yesno(@carrier.sort_and_segregate) %>
    </p>
    <p>
      <strong>Pool Distribution:</strong>
      <%= boolean_yesno(@carrier.pool_distribution) %>
    </p>
    <p>
      <strong>Participate in Recycling Programs:</strong>
      <%= boolean_yesno(@carrier.participate_in_recycling_programs) %>
    </p>
    <p>
      <strong>Scanning:</strong>
      <%= boolean_yesno(@carrier.scanning) %>
    </p>
    <p>
      <strong>Scanning Software:</strong>
      <%= @carrier.scanning_software %>
    </p>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">General Operations</h3>
  </div>
  <div class="panel-body">
    <p>
      <strong>Ability To Agree On A Two Year Contract:</strong>
      <%= boolean_yesno(@carrier.two_year_contract) %>
    </p>
    <p>
      <strong>Ability To Operate 7 Days A Week And On Bank Holidays:</strong>
      <%= boolean_yesno(@carrier.operate_year_round) %>
    </p>
    <p>
      <strong>Ability To Handle Cosmetic Products:</strong>
      <%= boolean_yesno(@carrier.handle_cosmetic_products) %>
    </p>
    <p>
      <strong>Accept 30 Day Payment Terms:</strong>
      <%= boolean_yesno(@carrier.accept_payment_in_thirty_days) %>
    </p>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Files</h3>
  </div>
  <div class="panel-body">
    <div class="col-sm-4">
      <% if @carrier.nda? %>
        <p><strong>NDA:</strong> - <%= link_to 'Delete', remove_carrier_nda_path %></p>
        <% if @carrier.imagenda? %>
          <%= link_to image_tag(@carrier.nda.url(:large)), @carrier.nda.url, :class => 'file-thumbnail' %>
        <% else %>
          <%= link_to @carrier.nda_file_name, @carrier.nda.url %>
        <% end %>
      <% else %>
        <p><strong>No NDA uploaded.</strong></p>
      <% end %>
    </div>

    <div class="col-sm-4">
      <% if @carrier.contract? %>
        <p><strong>Contract:</strong> - <%= link_to 'Delete', remove_carrier_contract_path %></p>
        <% if @carrier.imagecontract? %>
          <%= link_to image_tag(@carrier.contract.url(:large)), @carrier.contract.url, :class => 'file-thumbnail' %>
        <% else %>
          <%= link_to @carrier.contract_file_name, @carrier.contract.url %>
        <% end %>
      <% else %>
        <p><strong>No contract uploaded.</strong></p>
      <% end %>
    </div>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Additional Info</h3>
  </div>
  <div class="panel-body">
    <p>
      <strong>Comments:</strong>
      <%= @carrier.comments %>
    </p>
  </div>
</div>

<div class="row">
  <div class="col-sm-6">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Contacts At <%= @carrier.name %>.</h3>
      </div>
      <div class="panel-body">
        <% if @carrier.contacts.present? %>
          <% @carrier.contacts.each do |contact| %>
            <%= link_to contact.name, contact %><br>
          <% end %>
        <% else %>
          <strong>No contacts found for this carrier.</strong>
        <% end %>
      </div>
    </div>
  </div>

  <div class="col-sm-6">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Facilities belonging to <%= @carrier.name %>.</h3>
      </div>
      <div class="panel-body">
        <% if @carrier.facilities.present? %>
          <% @carrier.facilities.each do |facility| %>
            <%= link_to facility do %>
              <%= facility.address %>, <%= facility.city %>, <%= facility.state %>
            <% end %><br>
          <% end %>
        <% else %>
          <strong>No facilities found for this carrier.</strong>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="btn-group">
  <%= link_to 'Edit', edit_carrier_path(@carrier), class: 'btn btn-default' %>
  <%= link_to 'Back', carriers_path, class: 'btn btn-default' %>
</div>