config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  devise_for :users
  resources :facilities
  resources :carriers
  resources :contacts
  resources :messages

  resources :carriers do
    resources :contacts
    resources :facilities
  end

  root 'static_pages#home'

  get 'carrier/:id/remove_nda', to: 'carriers#remove_nda', as: 'remove_carrier_nda'
  get 'carrier/:id/remove_contract', to: 'carriers#remove_contract', as: 'remove_carrier_contract'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @messages = Message.all.order('created_at DESC')

    respond_to do |format|
      format.html
      format.json
    end
  end


end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_buttonpanels.html.erb
<div class="well">
  <p class="lead">Please take some time to fill out the information forms below.</p>
  <p>The information you provide will help us understand your business and allow us to easily contact you for future opportunities. Your information will remain secure in our database and will not be shared with outside parties.</p>

  <div class="col-md-4">
    <a class="buttonpanel-link" href="<%= new_carrier_path %>">
      <div class="buttonpanel buttonpanel-blue <%= 'buttonpanel-highlight' if current_user.carrier_name == nil and !current_user.admin %>">
        <span>
          <h3>Step 1: Carrier Registration</h3>
        </span>
      </div>
    </a>
  </div>

<% if current_user.carrier_name != nil or current_user.admin? %>
  <div class="col-md-4">
    <a class="buttonpanel-link <%= 'buttonpanel-disabled' if current_user.carrier_name == nil %>" href="<%= new_facility_path %>">
      <div class="buttonpanel buttonpanel-blue">
        <span>
          <h3>Step 2: Facility Registration</h3>
        </span>
      </div>
    </a>
  </div>
<% else %>
  <div class="col-md-4">
    <div class="buttonpanel buttonpanel-blue buttonpanel-disabled">
      <span>
        <h3>Step 2: Facility Registration</h3>
      </span>
    </div>
  </div>
<% end %>

<% if current_user.carrier_name != nil or current_user.admin? %>
  <div class="col-md-4">
    <a class="buttonpanel-link" href="<%= new_contact_path %>">
      <div class="buttonpanel buttonpanel-blue">
        <span>
          <h3>Step 3: Contact Registration</h3>
        </span>
      </div>
    </a>
  </div>
<% else %>
  <div class="col-md-4">
    <div class="buttonpanel buttonpanel-blue buttonpanel-disabled">
      <span>
        <h3>Step 3: Contact Registration</h3>
      </span>
    </div>
  </div>
<% end %>

  <div class="clearfix"></div>
</div>

app/views/static_pages/_developerlog.html.erb
<div class="well">
  <h4>Development Log</h4><hr>
  <p class="lead">Recent Changes:</p>
  <ul>
    <li>Added ability to upload NDA and Contract files to carriers.</li>
    <li>Non-admin users won't see full list of carriers.</li>
    <li>Contact cards now show states.</li>
    <li>Search fields are no longer case sensitive.</li>
    <li>Added more options to carrier and facility forms.</li>
    <li>An email goes to <span class="text-info">info@gumroandassociates.com</span> when a form is submitted.</li>
    <li>Carriers can fill out forms without signing up.</li>
    <li>Added Message Wall on home page for logged in users.</li>
    <li>Can now upload and delete contract files for carriers.</li>
    <li>Can now upload and delete NDA files for carriers.</li>
    <li>Added a comments field for contacts.</li>
    <li>Contacts' email addresses are now links that open up Outlook.</li>
    <li>Carriers detail pages now show associated contacts and facilities.</li>
    <li>Added some visual styling.</li>
    <li>Added more information to Carriers and Facilities pages.</li>
    <li>Tapping a Contact's phone # from a smartphone will call them.</li>
    <li>Asks if you're sure before deleting an entry.</li>
    <li>Added Edit and Delete functions to Carriers, Contacts and Facilities.</li>
    <li>Added success and error messages.</li>
    <li>Passwords are now encrypted.</li>
    <li>Added user account functionality.</li>
    <li>Joined Contacts and Facilities tables to Carriers table.</li>
    <li>Created tables for Carriers, Contacts, and Facilities.</li>
    <li>Database built.</li>
  </ul>
  <hr>
  <p class="lead">To Do:</p>
  <ul>
    <li>Add ability to type message to message wall directly from the home page.</li>
    <li>NDA functionality</li>
      <ul>
        <li>Add <code>NDA-expiration-date</code>, and <code>NDA-signed-by</code> to carriers.</li>
        <li>Send email to info@gumroandassociates.com when NDA expires.</li>
      </ul>
  </ul>
</div>

app/views/static_pages/_messagewall.html.erb
<div class="clearfix"></div>

<div class="well">
  <div class="row">
    <div class="col-sm-6">
      <h4>Message Wall</h4>
    </div>
    <div class="col-sm-6">
      <%= link_to new_message_path, remote: true, class: 'btn btn-success pull-right' do %>
        <i class="glyphicon glyphicon-plus" aria-hidden="true"></i> New Message
      <% end %>
    </div>
  </div>
  <div class="row">
    <div id="messages-form" style="display:none;"></div>
  </div>
</div>

<div class="well" id="messages-render">
<%= render @messages.limit(10) %>
</div>
<%= link_to 'See All Messages', messages_path %>

app/views/static_pages/home.html.erb
<%= image_tag("GnA_Logo.png", size: "150x150", class: "center-block", alt: "Gumro and Associates Logo" )%>
<h1 class="text-center">Gumro &amp; Associates</h1>
<h3 class="text-center">Carrier Management System</h3>

<% if user_signed_in? %>
  <%= render 'buttonpanels' %>
<% else %>
  <br><p class="lead text-center">Please
    <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-success' %> or
    <%= link_to 'Log In', new_user_session_path, class: 'btn btn-primary' %>
    to proceed.</p>
<% end %>

<% if current_user.try(:admin?) %>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= render 'messagewall' %>
    </div>
  </div>
<% end %>