config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  devise_for :users
  resources :facilities
  resources :carriers
  resources :contacts
  resources :messages

  resources :carriers do
    resources :contacts
    resources :facilities
  end

  root 'static_pages#home'

  get 'carrier/:id/remove_nda', to: 'carriers#remove_nda', as: 'remove_carrier_nda'
  get 'carrier/:id/remove_contract', to: 'carriers#remove_contract', as: 'remove_carrier_contract'

end

app/models/facility.rb
class Facility < ActiveRecord::Base
  belongs_to :carrier, dependent: :destroy

  validates :carrier, :address, :city, :state, :size, :terminal_door_count, :hours_of_operation, :average_equipment_age, :ratio_independant_company, :average_theft_rate, :vehicle_count_24, :vehicle_count_26, :vehicle_count_48, :vehicle_count_53, :vehicle_count_sprinter_vans, :vehicle_count_flat_beds, :vehicle_count_reefers, :presence => true

  def self.search(search)
    where("address LIKE ? OR city LIKE ?", "%#{search}%", "%#{search}%")
  end

  def self.searchState(searchState)
    where("state LIKE ?", "%#{search}%")
  end
end

app/controllers/facilities_controller.rb
class FacilitiesController < ApplicationController
  before_action :set_facility, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:new, :create]

  # GET /facilities
  # GET /facilities.json
  def index
    @search = Facility.ransack(params[:q])
    @facilities = @search.result
  end

  # GET /facilities/1
  # GET /facilities/1.json
  def show
    @carriers = Carrier.all
  end

  # GET /facilities/new
  def new
    @facility = Facility.new
    @carriers = Carrier.all
  end

  # GET /facilities/1/edit
  def edit
    @carriers = Carrier.all
  end

  # POST /facilities
  # POST /facilities.json
  def create
    @carriers = Carrier.all
    @facility = Facility.new(facility_params)
    if !current_user.admin?
      @facility.carrier_id = Carrier.find_by_name(current_user.carrier_name).id
    end

    respond_to do |format|
      if @facility.save
        # FormMailer.facility_email(@facility.city, @facility.id).deliver
        format.html { redirect_to :root, notice: 'Thank you for registering!' }
        format.json { render :root, status: :created, location: @facility }
      else
        format.html { render :new }
        format.json { render json: @facility.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /facilities/1
  # PATCH/PUT /facilities/1.json
  def update
    respond_to do |format|
      if @facility.update(facility_params)
        format.html { redirect_to @facility, notice: 'Facility was successfully updated.' }
        format.json { render :show, status: :ok, location: @facility }
      else
        format.html { render :edit }
        format.json { render json: @facility.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /facilities/1
  # DELETE /facilities/1.json
  def destroy
    @facility.destroy
    respond_to do |format|
      format.html { redirect_to facilities_url, notice: 'Facility was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_facility
      @facility = Facility.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def facility_params
      params.require(:facility).permit(:address, :city, :state, :carrier_id, :has_security, :has_CCTV, :has_fence, :has_sprinklers, :has_fire_alarm, :has_burglar_alarm, :has_drop_yard, :terminal_door_count, :hours_of_operation, :has_GPS, :has_alternate_fuel, :has_standard_equipment_types, :average_equipment_age, :size, :drivers_are_screened, :has_high_driver_turnover, :holds_driver_training, :average_theft_rate, :vehicle_count_24, :vehicle_count_26, :vehicle_count_48, :vehicle_count_53, :vehicle_count_sprinter_vans, :vehicle_count_flat_beds, :vehicle_count_reefers, :separate_caged_area_for_gas_tanks, :driver_scan, :independant_contractors, :company_drivers, :ratio_independant_company)
    end
end

app/helpers/facilities_helper.rb
module FacilitiesHelper
end

app/views/facilities/_form.html.erb
<%= form_for @facility, html: {class: 'form-horizontal'} do |f| %>
  <% if @facility.errors.any? %>
    <div class="alert alert-danger alert-dismissible" id="error_explanation" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <% @facility.errors.full_messages.each do |message| %>
        <p><%= message %></p>
      <% end %>
    </div>
  <% end %>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Location</h3>
    </div>
    <div class="panel-body">
      <% if current_user.try(:admin?) %>
        <div class="row form_group">
          <%= f.label :carrier, class: 'col-sm-2 control-label' %>
          <div class="col-sm-5">
            <%= f.select :carrier_id, options_for_select(@carriers.map{ |s| [s.name, s.id] }, params[:carrier_id]), include_blank: 'Select a carrier', class: 'form-control' %>
          </div>
        </div>
      <% end %>
      <div class="row form_group">
        <%= f.label :address, class: 'col-sm-2 control-label' %>
        <div class="col-sm-5">
          <%= f.text_field :address, class: 'form-control' %>
        </div>
      </div>
      <div class="row form_group">
        <%= f.label :city, class: 'col-sm-2 control-label' %>
        <div class="col-sm-5">
          <%= f.text_field :city, class: 'form-control' %>
        </div>
      </div>
      <div class="row form_group">
        <%= f.label :state, class: 'col-sm-2 control-label' %>
        <div class="col-sm-5">
          <%= f.text_field :state, class: 'form-control' %>
        </div>
      </div>
      <div class="row form_group">
        <%= f.label :size, "Size (sq ft)", class: 'col-sm-2 control-label' %>
        <div class="col-sm-5">
          <%= f.text_field :size, class: 'form-control' %>
        </div>
      </div>
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Facility</h3>
    </div>
    <div class="panel-body">
      <div class="form_control">
        <%= f.check_box :has_security %>
        <%= f.label :has_security %>
      </div>
      <div class="form_control">
        <%= f.check_box :has_CCTV %>
        <%= f.label :has_CCTV %>
      </div>
      <div class="form_control">
        <%= f.check_box :has_fence %>
        <%= f.label :has_fence %>
      </div>
      <div class="form_control">
        <%= f.check_box :has_sprinklers %>
        <%= f.label :has_sprinklers %>
      </div>
      <div class="form_control">
        <%= f.check_box :has_fire_alarm %>
        <%= f.label :has_fire_alarm %>
      </div>
      <div class="form_control">
        <%= f.check_box :has_burglar_alarm %>
        <%= f.label :has_burglar_alarm %>
      </div>
      <div class="form_control">
        <%= f.check_box :has_drop_yard %>
        <%= f.label :has_drop_yard %>
      </div>
      <div class="form_control">
        <%= f.check_box :separate_caged_area_for_gas_tanks %>
        <%= f.label :separate_caged_area_for_gas_tanks %>
      </div>
      <div class="form_control">
        <%= f.label :terminal_door_count %><br>
        <%= f.number_field :terminal_door_count %>
      </div>
      <div class="form_control">
        <%= f.label :hours_of_operation %><br>
        <%= f.text_field :hours_of_operation %>
      </div>
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Equipment</h3>
    </div>
    <div class="panel-body">
      <div class="form_control">
        <%= f.check_box :has_GPS %>
        <%= f.label :has_GPS %>
      </div>
      <div class="form_control">
        <%= f.check_box :has_alternate_fuel %>
        <%= f.label :has_alternate_fuel %>
      </div>
      <div class="form_control">
        <%= f.check_box :has_standard_equipment_types %>
        <%= f.label :has_standard_equipment_types %>
      </div>
      <div class="form_control">
        <%= f.label :average_equipment_age %> in years<br>
        <%= f.number_field :average_equipment_age %>
      </div>
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Drivers</h3>
    </div>
    <div class="panel-body">
      <div class="form_control">
        <%= f.check_box :drivers_are_screened %>
        <%= f.label :drivers_are_screened %>
      </div>
      <div class="form_control">
        <%= f.check_box :has_high_driver_turnover %>
        <%= f.label :has_high_driver_turnover %>
      </div>
      <div class="form_control">
        <%= f.check_box :holds_driver_training %>
        <%= f.label :holds_driver_training %>
      </div>
      <div class="form_control">
        <%= f.check_box :driver_scan %>
        <%= f.label :driver_scan, "Driver scanning capabilities?" %>
      </div>
      <div class="form_control">
        <%= f.check_box :independant_contractors %>
        <%= f.label :independant_contractors, "Have independant contractors?" %>
      </div>
      <div class="form_control">
        <%= f.check_box :company_drivers %>
        <%= f.label :company_drivers, "Have company drivers?" %>
      </div>
      <div class="form_control">
        <%= f.label :ratio_independant_company, "Independant to company driver ratio" %> <br>
        <%= f.text_field :ratio_independant_company %>
      </div>
      <div class="form_control">
        <%= f.label :average_theft_rate %> <br>
        <%= f.number_field :average_theft_rate %>
      </div>
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Vehicle Counts</h3>
    </div>
    <div class="panel-body">
      <div class="form_control">
        24'<br>
        <%= f.number_field :vehicle_count_24 %>
      </div>
      <div class="form_control">
        26'<br>
        <%= f.number_field :vehicle_count_26 %>
      </div>
      <div class="form_control">
        48'<br>
        <%= f.number_field :vehicle_count_48 %>
      </div>
      <div class="form_control">
        53'<br>
        <%= f.number_field :vehicle_count_53 %>
      </div>
      <div class="form_control">
        Sprinter Vans<br>
        <%= f.number_field :vehicle_count_sprinter_vans %>
      </div>
      <div class="form_control">
        Flat Beds<br>
        <%= f.number_field :vehicle_count_flat_beds %>
      </div>
      <div class="form_control">
        Reefers<br>
        <%= f.number_field :vehicle_count_reefers %>
      </div>
    </div>
  </div>

  <p class="text-muted">This form contains proprietary information, trade secret information, copyrighted materials, or any combination thereof and will not be reproduced, published, used, or otherwise disseminated without your express written permission. The contents of this form are protectable under the Economic Espionage Act, 18 U.S.C. §1831 et seq., the Electronic Communications Privacy Act, 18 U.S.C. §2510 et seq., the Copyright Act, 17 U.S.C. §101 et seq., the Michigan Uniform Trade Secret Act §445.1901 et seq., as well as common law; applicable law provides criminal remedies, civil remedies, or both for the unauthorized reproduction, publication, use, or dissemination of the contents of this form or any attached files.  This form is intended solely for the use of the individual or entity addressed above; if you have received this form in error, please notify the sender.</p>

  <div class="actions">
    <%= f.submit 'Submit', :class => 'btn btn-primary' %>
  </div><br>
<% end %>

app/views/facilities/edit.html.erb
<h1>Editing Facility</h1>

<%= render 'form' %>

<div class="btn-group">
  <%= link_to 'Show', @facility, class: 'btn btn-default' %>
  <%= link_to 'Back', facilities_path, class: 'btn btn-default' %>
</div>

app/views/facilities/index.html.erb
<h1>Facilities</h1>

<div class="well" style="margin: 40px 0;">
  <div class="row">
    <div class="col-sm-4">
      <%= search_form_for @search do |f| %>
        <div class="input-group">
          <%= f.text_field :carrier_name_cont, class: 'form-control', placeholder: "Carrier Name"  %>
          <div class="input-group-btn">
            <%= button_tag "", type: 'submit', class: "btn btn-default glyphicon glyphicon-search pull-right" %>
          </div>
        </div>
      <% end %>

      <%= search_form_for @search do |f| %>
        <div class="input-group">
          <%= f.text_field :city_cont, class: 'form-control', placeholder: "City" %>
          <div class="input-group-btn">
            <%= button_tag "", type: 'submit', class: "btn btn-default glyphicon glyphicon-search pull-right" %>
          </div>
        </div>
      <% end %>

      <%= search_form_for @search do |f| %>
        <div class="input-group">
          <%= f.text_field :state_cont, class: 'form-control', placeholder: "State" %>
          <div class="input-group-btn">
            <%= button_tag "", type: 'submit', class: "btn btn-default glyphicon glyphicon-search pull-right" %>
          </div>
        </div>
      <% end %>

      <%= search_form_for @search do |f| %>
        <div class="input-group">
          <%= f.label :has_security_true, "Has Security" %>
          <%= f.check_box :has_security_true, :checked => @search.has_security_true, :unchecked => @search.has_security_false, placeholder: "State" %>
          <div class="input-group-btn">
            <%= button_tag "", type: 'submit', class: "btn btn-default glyphicon glyphicon-search pull-right" %>
          </div>
        </div>
      <% end %>


      <%= link_to 'Reset', facilities_path, class: 'btn btn-default' %>

    </div>

    <div class="col-sm-4 col-sm-offset-4">
      <%= link_to new_facility_path, class: 'btn btn-success pull-right' do %>
        <i class="glyphicon glyphicon-plus" aria-hidden="true"></i> New Facility
      <% end %>
    </div>
  </div>
</div>

<% @facilities.each do |facility| %>
  <div class="card">
    <div class="content">

      <!-- edit and delete buttons -->
      <div class="btn-group pull-right" role="group" aria-label="...">
        <%= link_to edit_facility_path(facility), class: 'btn btn-default' do %>
          <i class="glyphicon glyphicon-edit" aria-hidden="true"></i>
        <% end %>
        <%= link_to facility, method: :delete, data: { confirm: 'Woah! Careful, buddy. You sure you wanna delete this facility?' }, class: 'btn btn-danger' do %>
          <i class="glyphicon glyphicon-trash" aria-hidden="true"></i>
        <% end %>
      </div>

      <span class="title"><%= link_to facility.carrier.name, facility %></span>
      <p><span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span> <%= facility.address %>, <%= facility.city %>, <%= facility.state %></p>
    </div>
  </div>
<% end %>

app/views/facilities/new.html.erb
<h1>New Facility</h1>

<%= render 'form' %><hr>

<% if current_user.try(:admin?) %>
  <%= link_to 'Back', facilities_path, class: 'btn btn-default' %>
<% else %>
  <%= link_to 'Back', root_path, class: 'btn btn-default' %>
<% end %>

app/views/facilities/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Location</h3>
  </div>
  <div class="panel-body">
    <p>
      <strong>Carrier:</strong>
      <%= @facility.carrier.name %>
    </p>

    <p>
      <strong>Address:</strong>
      <%= @facility.address %>
    </p>

    <p>
      <strong>City:</strong>
      <%= @facility.city %>
    </p>

    <p>
      <strong>State:</strong>
      <%= @facility.state %>
    </p>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Facility</h3>
  </div>
  <div class="panel-body">
    <p>
      <strong>Size:</strong>
      <%= @facility.size %>
    </p>

    <p>
      <strong>Has Security:</strong>
      <%= boolean_yesno(@facility.has_security) %>
    </p>

    <p>
      <strong>Has CCTV:</strong>
      <%= boolean_yesno(@facility.has_CCTV) %>
    </p>

    <p>
      <strong>Has Fence:</strong>
      <%= boolean_yesno(@facility.has_fence) %>
    </p>

    <p>
      <strong>Has Sprinklers:</strong>
      <%= boolean_yesno(@facility.has_sprinklers) %>
    </p>

    <p>
      <strong>Has Fire Alarm:</strong>
      <%= boolean_yesno(@facility.has_fire_alarm) %>
    </p>

    <p>
      <strong>Has Burglar Alarm:</strong>
      <%= boolean_yesno(@facility.has_burglar_alarm) %>
    </p>

    <p>
      <strong>Has Drop Yard:</strong>
      <%= boolean_yesno(@facility.has_drop_yard) %>
    </p>

    <p>
      <strong>Separate caged area for gas tanks:</strong>
      <%= boolean_yesno(@facility.separate_caged_area_for_gas_tanks) %>
    </p>

    <p>
      <strong>Terminal Door Count:</strong>
      <%= @facility.terminal_door_count %>
    </p>

    <p>
      <strong>Hours of Operation:</strong>
      <%= @facility.hours_of_operation %>
    </p>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Equipment</h3>
  </div>
  <div class="panel-body">
    <p>
      <strong>Has GPS:</strong>
      <%= boolean_yesno(@facility.has_GPS) %>
    </p>

    <p>
      <strong>Has Alternate Fuel:</strong>
      <%= boolean_yesno(@facility.has_alternate_fuel) %>
    </p>

    <p>
      <strong>Has Standard Equipment Types:</strong>
      <%= boolean_yesno(@facility.has_standard_equipment_types) %>
    </p>

    <p>
      <strong>Average Equipment Age:</strong>
      <%= @facility.average_equipment_age %>
    </p>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Drivers</h3>
  </div>
  <div class="panel-body">
    <p>
      <strong>Drivers Are Screened:</strong>
      <%= boolean_yesno(@facility.drivers_are_screened) %>
    </p>

    <p>
      <strong>Has High Driver Turnover:</strong>
      <%= boolean_yesno(@facility.has_high_driver_turnover) %>
    </p>

    <p>
      <strong>Holds Driver Training:</strong>
      <%= boolean_yesno(@facility.holds_driver_training) %>
    </p>

    <p>
      <strong>Average Theft Rate:</strong>
      <%= boolean_yesno(@facility.average_theft_rate) %>
    </p>

    <p>
      <strong>Driver Scanning Capabilities:</strong>
      <%= boolean_yesno(@facility.driver_scan) %>
    </p>

    <p>
      <strong>Have Independant Contractors?:</strong>
      <%= boolean_yesno(@facility.independant_contractors) %>
    </p>

    <p>
      <strong>Have Company Drivers?:</strong>
      <%= boolean_yesno(@facility.company_drivers) %>
    </p>

    <p>
      <strong>Independant to Company Driver Ratio:</strong>
      <%= @facility.ratio_independant_company %>
    </p>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Vehicle Counts</h3>
  </div>
  <div class="panel-body">
    <p>
      <strong>Vehicle Count - 24':</strong>
      <%= @facility.vehicle_count_24 %>
    </p>

    <p>
      <strong>Vehicle Count - 26':</strong>
      <%= @facility.vehicle_count_26 %>
    </p>

    <p>
      <strong>Vehicle Count - 48':</strong>
      <%= @facility.vehicle_count_48 %>
    </p>

    <p>
      <strong>Vehicle Count - 53':</strong>
      <%= @facility.vehicle_count_53 %>
    </p>

    <p>
      <strong>Vehicle Count - Sprinter Vans:</strong>
      <%= @facility.vehicle_count_sprinter_vans %>
    </p>

    <p>
      <strong>Vehicle Count - Flat Beds:</strong>
      <%= @facility.vehicle_count_flat_beds %>
    </p>

    <p>
      <strong>Vehicle Count - Reefers:</strong>
      <%= @facility.vehicle_count_reefers %>
    </p>
  </div>
</div>

<div class="btn-group">
  <%= link_to 'Edit', edit_facility_path(@facility), class: 'btn btn-default' %>
  <%= link_to 'Back', facilities_path, class: 'btn btn-default' %>
</div>