config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  devise_for :users
  resources :facilities
  resources :carriers
  resources :contacts
  resources :messages

  resources :carriers do
    resources :contacts
    resources :facilities
  end

  root 'static_pages#home'

  get 'carrier/:id/remove_nda', to: 'carriers#remove_nda', as: 'remove_carrier_nda'
  get 'carrier/:id/remove_contract', to: 'carriers#remove_contract', as: 'remove_carrier_contract'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Gumro Carrier Management System</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>

<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><%= image_tag("GnA_Logo.png", size: "25x25", alt: "Gumro and Associates Logo" )%> Gumro CMS</a>
    </div>
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <% if current_user.try(:admin?) %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'Carriers', carriers_path %></li>
          <li><%= link_to 'Facilities', facilities_path %></li>
          <li><%= link_to 'Contacts', contacts_path %></li>
          <li><%= link_to 'Account', edit_user_registration_path %></li>
          <li><%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %></li>
        </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-right">
          <% if !user_signed_in? %>
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
            <li><%= link_to 'Log In', new_user_session_path %></li>
          <% else %>
            <li><%= link_to 'Account', edit_user_registration_path %></li>
            <li><%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %></li>
          <% end %>
        </ul>
      <%end %>
    </div>
  </div>
</nav>

<div id="main-container" class="container">
  <div class="row">
    <div class="col-xs-12">
      <% if notice %>
        <div class="alert alert-success alert-dismissable" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= notice %>
        </div>
      <% end %>
      <% if alert %>
        <div class="alert alert-danger alert-dismissable" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= alert %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12">
      <%= yield %>
    </div>
  </div>
</div>

</body>
</html>